<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2023-10-14 20:19:25
 */
return [
    'all' => [
        'class' => 'frontend\\assets\\AppAsset',
        'basePath' => '@webroot/',
        'baseUrl' => '@web/',
        'jsOptions' => [
            'defer' => 'defer',
        ],
        'js' => [
            'assets/all-a80de6979ed06736b4949a31457ee1ed.min.js',
        ],
        'css' => [
            'assets/all-7d936fa85afb575a59f1d381cc0d0bcb.min.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'frontend\\assets\\NpmAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
    'frontend\\assets\\AppAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'frontend\\assets\\NpmAsset',
            'all',
        ],
    ],
];